# XCloud后端服务配置文件

# 应用配置
app:
  name: "XCloud多云对账平台"
  version: "1.0.0"
  mode: "debug"  # debug, release, test

# 服务器配置
server:
  port: "8080"
  read_timeout: 60
  write_timeout: 60

# 数据库配置
database:
  host: "localhost"
  port: 5432
  name: "xcloud"
  username: "xcloud"
  password: "xcloud123"
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime: 1800  # 30分钟

# Redis配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

# JWT配置
jwt:
  secret: "xcloud-jwt-secret-key-2024"
  expire_hours: 24
  refresh_expire_hours: 168  # 7天

# 日志配置
log:
  level: "info"  # trace, debug, info, warn, error, fatal, panic
  format: "json"  # json, text
  output: "stdout"  # stdout, file

# 云平台API配置
cloud_providers:
  tencent:
    endpoint: "https://partners.tencentcloudapi.com"
    version: "v1"
    timeout: 30
    retry_count: 3
  alibaba:
    endpoint: "https://ecs.aliyuncs.com"
    version: "2014-05-26"
    timeout: 30
    retry_count: 3
  huawei:
    endpoint: "https://ecs.myhuaweicloud.com"
    version: "v1"
    timeout: 30
    retry_count: 3
  aws:
    endpoint: "https://aws.amazon.com"
    version: "2016-11-15"
    timeout: 30
    retry_count: 3

# 消息队列配置
rabbitmq:
  url: "amqp://xcloud:xcloud123@localhost:5672/"
  exchange: "xcloud"
  queue_prefix: "xcloud"

# 数据同步配置
sync:
  interval: 3600  # 同步间隔（秒）
  batch_size: 1000
  max_workers: 5

# 返佣计算配置
commission:
  precision: 4  # 小数精度
  currency: "CNY"
  batch_size: 10000

# 文件上传配置
upload:
  max_size: 10485760  # 10MB
  allowed_types: ["image/jpeg", "image/png", "application/pdf", "text/csv", "application/vnd.ms-excel"]
  storage_path: "./uploads"